### ISSUE TITLE
labyrinth_rs 1.0.0

### ISSUE THREAD

**Issue by asuratos** [asuratos/labyrinth-rs#3]
# Overview

Central tracker for tasks related to the release of the labyrinth_rs package.

# Goals and Requirements

The core goals of this package are:
- To provide a way for novice roguelike developers to generate basic, usable maps without extensive knowledge of map generation or pathfinding algorithms
- To provide a way for more advanced users to customize and play around with the generation algorithms without diving into algorithm minutia

Therefore, at 1.0.0, the package MUST have:
1. Roguelike-style map generation that is simple, but with extensible complexity options
2. Easy to use Maps(Labyrinths) that implement the common pathfinding algorithms

# Member Crates
In order to fulfill the above Goals and Requirements, the package is split into two crates:
- **labyrinth_map**, which provides a map representation struct that
  - preimplements common pathfinding and FoV traits (from bracket_lib) for ease of use, and
  - allows the user to define their own tiles and movement types without the need to fiddle with pathfinding implementation
- **daedalus**, which provides a way to easily generate maps (Labyrinths)

Users who want to code their own custom map generation algorithms can use labyrinth_map directly, while those who don't want to can use the higher-level API of daedalus instead.

# Tasks
- [ ] labyrinth_map
  - [ ] Implement Maps
    - [ ] Pathfinding
      - [x] Pathfinding using basic movement types (walking, flying, swimming, or combinations thereof)
      - [x] Pathfinding over user-defined movement types 
      - [x] #4
    - [ ] Map editing functionality
      - [x] Tile access/edit
      - [x] add Movement type
    - [ ] Map accessing functionality
      - [x] Single tile access
      - [ ] Iterator implementation
        - [ ] Iterator over all tiles
          - [ ] iter()
          - [ ] iter_mut() 
        - [ ] filtered (by accessibility, kind, etc)
          - [ ] iter_enterable()
          - [ ] iter_enterable_mut()
- [ ] daedalus
  - [ ] Implement generation algorithms
