### ISSUE TITLE
Test pathfinding functionality

### ISSUE THREAD

**Issue by asuratos** [asuratos/labyrinth-rs#4]
Pathfinding functionality of Map objects in the crate. 

The pathfinding algorithms themselves are implemented in bracket-pathfinding, so I can safely assume that those work properly. Instead, this task is for testing that the structs in the crate that will be used for pathfinding implement them properly.

## Tasks
- [x] Test Pathfinding
  - [x] Test get_available_exits for each movement type
    - [x] Walk
      - [x] can only enter floor tiles
    - [x] Fly
      - [x] can enter floor, water, lava
    - [x] Swim
      - [x] can enter water
    - [x] User-defined types
    - [x] Mix of multiple movement types
      - [x] Mix of predefined move types
      - [x] Mix of user-defined move types
      - [x] Mix of user-defined and predefined move types
