### ISSUE TITLE
Crate Separation

### ISSUE THREAD

**Issue by asuratos** [asuratos/labyrinth-rs#7]
Separating the Map (now Labyrinth) from the LabyrinthGenerator crates, so that they can eventually be used separately

## Tasks 
- [x] Shift around the directory structure
- [x] Map crate
  - [x] Change names to avoid ambiguity
    - [x] Map -> Labyrinth2D
    - [x] Tile -> something else?
  - [x] Documentation pass
    - [x] Doctests pass
    - [x] Documentation should not reference old names
      - [x] tiles.rs
      - [x] map_objects.rs
- [x] Generator crate
  - [x] Think of new name (Daedalus? as in the builder of the Labyrinth)

**Comment by asuratos** [comment]
Decided to stick with name Deadalus
